// Characters (skins): same sprite, different palette + optional procedural accessories (render/skins.js).
// `price` in coins (0 = owned from the start), `rarity` 0 comum, 1 raro, 2 épico, 3 lendário.
// Everything here is cosmetic: no character changes the gameplay.
// Optional fields: `desc` (one line, pt-BR), `acc` (accessories, see render/skins.js), `trail` { kind, color }
// (small particles while moving fast: smoke, fire, bubble, leaf, spark, star), `aura` (soft glow colour),
// `alpha` (see-through sprite). Original characters, only INSPIRED by styles (no trademarked names/designs).
const SKINS = [
  { id: 'white', name: 'Ninja Branco', price: 0, rarity: 0, desc: 'O clássico: faixa preta, roupa branca e muita mola nas pernas.',
    out: '#1b1b26', rim: 'rgba(160,215,255,0.95)',
    body: ['#ffffff', '#e9edf3', '#a4adbf'], head: ['#ffffff', '#eef1f6', '#bfc6d4', '#939cb0'],
    limb: '#f4f5f8', limbBack: '#d9dce4', foot: '#e3e6ee', footBack: '#cfd3dc', hand: '#e3e6ee',
    limbShade: 'rgba(110,120,150,0.45)', limbHi: 'rgba(255,255,255,0.85)', spec: 'rgba(255,255,255,0.95)',
    band: '#15151c', bandGrad: ['#3d4052', '#17171f', '#07070b'], visor: ['#363c55', '#0e1018'], eye: '#ffffff',
    occl: 'rgba(40,45,75,0.2)' },
  { id: 'black', name: 'Ninja Sombra', price: 500, rarity: 0, desc: 'Some no escuro da noite; só os olhos aparecem.',
    out: '#05050a', rim: 'rgba(150,170,220,0.75)',
    body: ['#6b7080', '#383b46', '#17181e'], head: ['#737888', '#454956', '#272a33', '#141519'],
    limb: '#3c3f4a', limbBack: '#2b2d36', foot: '#34363f', footBack: '#25272f', hand: '#3c3f4a',
    limbShade: 'rgba(0,0,0,0.45)', limbHi: 'rgba(255,255,255,0.3)', spec: 'rgba(255,255,255,0.5)',
    band: '#0a0a0e', bandGrad: ['#4a4d5c', '#1c1d24', '#050507'], visor: ['#7c86a3', '#3a4157'], eye: '#ffffff',
    occl: 'rgba(0,0,0,0.3)' },
  { id: 'red', name: 'Ninja Rubro', price: 500, rarity: 0, desc: 'Vermelho de coragem, do capuz até a ponta da faixa.',
    out: '#1a0a0c', rim: 'rgba(255,190,170,0.9)',
    body: ['#ff9a90', '#e3282e', '#8c0f15'], head: ['#ffa69d', '#ea3a40', '#b81c23', '#7a0b11'],
    limb: '#2c2c35', limbBack: '#202028', foot: '#26262e', footBack: '#1b1b22', hand: '#2c2c35',
    limbShade: 'rgba(0,0,0,0.45)', limbHi: 'rgba(255,255,255,0.32)', spec: 'rgba(255,255,255,0.85)',
    band: '#111116', bandGrad: ['#3d4052', '#17171f', '#07070b'], visor: ['#363c55', '#0e1018'], eye: '#ffffff',
    occl: 'rgba(60,0,0,0.25)' }
];

// Builds a full palette from a few key colours (all #rrggbb), so each new character stays short
function skinPal(o) {
  const m = o.main, hc = o.headCol || m, l = o.limb || shadeHex(m, -0.35), f = o.foot || shadeHex(l, -0.12);
  const p = {
    out: '#120c16', rim: 'rgba(255,255,255,0.6)',
    body: [shadeHex(m, 0.45), m, shadeHex(m, -0.45)],
    head: [shadeHex(hc, 0.55), shadeHex(hc, 0.15), shadeHex(hc, -0.2), shadeHex(hc, -0.45)],
    limb: l, limbBack: shadeHex(l, -0.25), foot: f, footBack: shadeHex(f, -0.3), hand: o.hand || l,
    limbShade: 'rgba(0,0,0,0.4)', limbHi: 'rgba(255,255,255,0.35)', spec: 'rgba(255,255,255,0.8)',
    band: o.band, bandGrad: [shadeHex(o.band, 0.35), o.band, shadeHex(o.band, -0.5)],
    visor: ['#363c55', '#0e1018'], eye: '#ffffff', occl: 'rgba(0,0,0,0.25)'
  };
  for (const k in o) p[k] = o[k];
  return p;
}
SKINS.push(
  // --- Clã dos Demônios Elementais: cada mestre comanda seu exército de ninjas-demônio (ids 'oni*' mantidos p/ saves) ---
  skinPal({ id: 'oniAbismo', name: 'Shinobi do Abismo', price: 600, rarity: 0,
    desc: 'Comanda o exército de ninjas-demônio das sombras, que atravessam paredes como fumaça.',
    main: '#3a2a5c', limb: '#241a38', band: '#0d0a14', eye: '#ffe14d', rim: 'rgba(190,160,255,0.7)',
    acc: { horns: { style: 'small', col: '#d9d2e9' }, eyeGlow: '#ffe14d', body: { pattern: 'smoke', col: '#7a5cff' } },
    trail: { kind: 'smoke', color: '#7a5cff' } }),
  skinPal({ id: 'oniMontanha', name: 'Guardião da Montanha', price: 700, rarity: 0,
    desc: 'Pesado como rocha: seu exército de ninjas-demônio de pedra nunca recua um passo.',
    main: '#8a6f52', limb: '#4a3b2c', band: '#2e241a', eye: '#ffb35a',
    acc: { horns: { style: 'big', col: '#cfc6b4' }, pads: { col: '#9aa0a8', rock: true }, body: { pattern: 'cracks', col: '#4a3b2c' } },
    trail: { kind: 'smoke', color: '#c9b79a' } }),
  skinPal({ id: 'oniVendaval', name: 'Kunoichi do Vendaval', price: 800, rarity: 0,
    desc: 'Lidera ninjas-demônio do vento que correm no ar e somem num redemoinho.',
    main: '#7fc89a', limb: '#3f6b58', band: '#2c4a3e', rim: 'rgba(230,255,240,0.8)',
    acc: { horns: { style: 'small', col: '#f2fff4' }, back: [{ type: 'scarf', col: '#e9fff0' }], body: { pattern: 'swirl', col: '#e9fff0' } },
    trail: { kind: 'leaf', color: '#b9f0a0' } }),
  skinPal({ id: 'oniFloresta', name: 'Sentinela da Floresta', price: 800, rarity: 0,
    desc: 'Seu exército de ninjas-demônio brota do chão e se esconde entre as folhas.',
    main: '#4f8a3a', limb: '#2f4a22', band: '#5a3a1e', eye: '#d6ff7a',
    acc: { horns: { style: 'antler', col: '#7a5230', leaf: '#7fd04a' }, eyeGlow: '#d6ff7a', body: { pattern: 'leaves', col: '#8fd45a' } },
    trail: { kind: 'leaf', color: '#7fd04a' } }),
  skinPal({ id: 'oniChama', name: 'Ninja da Chama', price: 1200, rarity: 1,
    desc: 'Comanda um exército de ninjas-demônio de brasa que deixam pegadas de fogo.',
    main: '#e8501f', limb: '#3a1410', band: '#2a0a06', eye: '#ffd23f', rim: 'rgba(255,210,120,0.9)',
    acc: { horns: { style: 'big', col: '#2a1a14' }, eyeGlow: '#ffb030', body: { pattern: 'flames', col: '#ffc040' } },
    trail: { kind: 'fire', color: '#ff8a2a' } }),
  skinPal({ id: 'oniMare', name: 'Shinobi da Maré', price: 1200, rarity: 1,
    desc: 'Seu exército de ninjas-demônio surge das ondas, escorregadio como água.',
    main: '#1f8fb8', limb: '#0f3c5a', band: '#0a2238', eye: '#9ff6ff', rim: 'rgba(170,240,255,0.9)',
    acc: { crest: { style: 'fin', col: '#6fe0ff' }, eyeGlow: '#7fefff', body: { pattern: 'scales', col: '#9fe6ff' } },
    trail: { kind: 'bubble', color: '#bff3ff' } }),
  skinPal({ id: 'oniTrovao', name: 'Ninja do Trovão', price: 1500, rarity: 1,
    desc: 'Cada passo é um estalo: seus ninjas-demônio atacam na velocidade do raio.',
    main: '#2b2f6b', limb: '#181a3c', band: '#e0b020', eye: '#fff36a', rim: 'rgba(255,240,140,0.8)',
    acc: { horns: { style: 'bolt', col: '#ffd23f' }, eyeGlow: '#fff36a', body: { pattern: 'bolt', col: '#ffd23f' } },
    trail: { kind: 'spark', color: '#fff36a' } }),
  skinPal({ id: 'oniAco', name: 'Samurai de Aço', price: 1600, rarity: 1,
    desc: 'Armadura de aço temperado; seu exército de ninjas-demônio ressoa como um gongo.',
    main: '#8f9aa8', headCol: '#b8c0cc', limb: '#4a525e', band: '#2a2f38', eye: '#ff5a4a', rim: 'rgba(230,240,255,0.95)',
    acc: { crest: { style: 'blade', col: '#dfe5ee' }, eyeGlow: '#ff5a4a', pads: { col: '#c3cad4' }, body: { pattern: 'plates', col: '#5a636f' } },
    trail: { kind: 'spark', color: '#ffd27f' } }),
  skinPal({ id: 'oniLua', name: 'Andarilho da Lua', price: 2200, rarity: 2,
    desc: 'Só aparece à noite; seus ninjas-demônio se movem entre os raios do luar.',
    main: '#3a3f7a', headCol: '#aab0d8', limb: '#23264d', band: '#1a1c3a', eye: '#ffffff', rim: 'rgba(210,225,255,0.95)',
    acc: { crest: { style: 'moon', col: '#f4f1d0' }, eyeGlow: '#cfe3ff', body: { pattern: 'stars', col: '#e8ecff' } },
    trail: { kind: 'star', color: '#e8ecff' }, aura: '#9fb4ff' }),
  skinPal({ id: 'oniCeu', name: 'Mestre do Céu', price: 2400, rarity: 2,
    desc: 'Plana acima das nuvens com um exército de ninjas-demônio alados.',
    main: '#6fb8f5', limb: '#2d5f9a', band: '#2d5f9a', visor: ['#eaf5ff', '#a9cdf0'], eye: '#1d3b66', rim: 'rgba(255,255,255,0.95)',
    acc: { horns: { style: 'small', col: '#ffffff' }, back: [{ type: 'wings', col: '#ffffff' }], body: { pattern: 'clouds', col: '#ffffff' } },
    trail: { kind: 'leaf', color: '#ffffff' }, aura: '#bfe3ff' }),
  skinPal({ id: 'oniImperador', name: 'Imperador das Sombras', price: 5000, rarity: 3,
    desc: 'Senhor de todos os exércitos de ninjas-demônio. Dizem que nunca caiu de nenhuma parede.',
    main: '#2a1420', limb: '#160a12', band: '#c9a227', eye: '#ff3a3a', rim: 'rgba(255,200,90,0.9)',
    acc: { horns: { style: 'crown', col: '#e8c048' }, eyeGlow: '#ff3a3a', collar: { col: '#c9a227' },
      back: [{ type: 'cloak', col: '#6a0a18', lining: '#c9a227' }], body: { pattern: 'royal', col: '#e8c048' } },
    trail: { kind: 'fire', color: '#ff4a3a' }, aura: '#ff3a3a' }),
  // --- Ninjas de vila escondida (estilo anime de ninja) ---
  skinPal({ id: 'raposa', name: 'Ninja Raposa', price: 1500, rarity: 1,
    desc: 'Macacão laranja, coragem sem fim e um espírito de raposa guardado lá dentro.',
    main: '#ff8a1f', limb: '#f07a12', foot: '#1d2a4a', hand: '#f4d2a8', band: '#1f3a7a', eye: '#7fd0ff',
    acc: { ears: { style: 'fox', col: '#ff8a1f', inner: '#fff1d6' }, crest: { style: 'plate', col: '#c9d2e0', sym: 'swirl' },
      back: [{ type: 'tails', n: 1, col: '#ff8a1f', tip: '#fff6e6' }], body: { pattern: 'jumpsuit', col: '#1d2a4a' } },
    trail: { kind: 'star', color: '#ffb347' } }),
  skinPal({ id: 'lotus', name: 'Olhar de Lótus', price: 1300, rarity: 1,
    desc: 'Olhos claros que enxergam através das paredes; luta com toques suaves.',
    main: '#e4dcf3', limb: '#6a5a8a', band: '#4a3a6a', visor: ['#f6f2ff', '#cfc4ec'], eye: '#a898ff', rim: 'rgba(255,255,255,0.95)',
    acc: { crest: { style: 'plate', col: '#c9d2e0', sym: 'lotus' }, eyeGlow: '#c8bcff', body: { pattern: 'lotus', col: '#b58ad8' } },
    trail: { kind: 'leaf', color: '#ffc4e6' } }),
  skinPal({ id: 'luaRubra', name: 'Renegado da Lua Rubra', price: 3000, rarity: 2,
    desc: 'Deixou a vila para trás. Seu manto de luas vermelhas assusta até os demônios.',
    main: '#17171f', limb: '#22222c', band: '#3a3a46', eye: '#ff2a3a', rim: 'rgba(255,120,130,0.6)',
    acc: { crest: { style: 'plate', col: '#9aa0aa', sym: 'scratch' }, eyeGlow: '#ff2a3a', collar: { col: '#17171f', high: true },
      back: [{ type: 'cloak', col: '#17171f', lining: '#b0142a', moons: true }], body: { pattern: 'moons', col: '#c0142a' } },
    trail: { kind: 'leaf', color: '#c0142a' } }),
  // --- Cinema / anime / games (inspirações, personagens originais) ---
  skinPal({ id: 'pirata', name: 'Ninja Pirata', price: 900, rarity: 0,
    desc: 'Trocou o navio pela parede, mas não larga o chapéu nem o tapa-olho.',
    main: '#2a4a7a', limb: '#3a2a1a', band: '#c0392b', eye: '#ffffff',
    acc: { hat: { style: 'tricorn', col: '#1d1d22', trim: '#e8c048' }, patch: '#0b0b0e', body: { pattern: 'coat', col: '#e8c048' } },
    trail: { kind: 'star', color: '#ffd700' } }),
  skinPal({ id: 'leques', name: 'Kunoichi dos Leques', price: 1200, rarity: 1,
    desc: 'Abre os leques e o vento faz o resto.',
    main: '#d6337a', limb: '#5a1a3a', band: '#2a0a1a', eye: '#ffffff', rim: 'rgba(255,190,220,0.9)',
    acc: { back: [{ type: 'fans', col: '#ffd23f', col2: '#d6337a' }], hair: { col: '#2a0a1a' }, body: { pattern: 'sash', col: '#ffd23f' } },
    trail: { kind: 'leaf', color: '#ffb3d9' } }),
  skinPal({ id: 'robo', name: 'Robô Ninja', price: 1500, rarity: 1,
    desc: 'Modelo NJ-01: parafusos apertados, sensores ligados, pulo calibrado.',
    main: '#c9ced8', headCol: '#dfe3ea', limb: '#6a7280', band: '#e8323c', visor: ['#1a1f2a', '#05070a'], eye: '#ff3a3a',
    acc: { antenna: { col: '#9aa0aa', tip: '#ff3a3a' }, eyeGlow: '#ff3a3a', bolts: '#8a909c', body: { pattern: 'panel', col: '#7a8290' } },
    trail: { kind: 'spark', color: '#7af0ff' } }),
  skinPal({ id: 'samuraiCego', name: 'Samurai Cego', price: 1800, rarity: 1,
    desc: 'Não vê, mas ouve cada moeda caindo. Sua bengala esconde uma lâmina.',
    main: '#6f7684', limb: '#3f434c', band: '#2a2c33',
    acc: { hat: { style: 'kasa', col: '#d9b56a' }, blind: '#efe9dc', back: [{ type: 'sword', col: '#a07a4a', blade: '#dfe5ee' }], body: { pattern: 'kimono', col: '#3f434c' } },
    trail: { kind: 'spark', color: '#ffffff' } }),
  skinPal({ id: 'panda', name: 'Mestre Panda', price: 2000, rarity: 2,
    desc: 'Guerreiro fofinho do kung fu: ninguém espera um chute desses.',
    main: '#2a2a30', headCol: '#f6f6f6', limb: '#1d1d22', band: '#c0392b', visor: ['#1d1d22', '#0a0a0e'], rim: 'rgba(255,255,255,0.8)',
    acc: { ears: { style: 'panda', col: '#1d1d22' }, body: { pattern: 'belly', col: '#f2f2f2' } },
    trail: { kind: 'leaf', color: '#8fd14f' } }),
  skinPal({ id: 'fantasma', name: 'Ninja Fantasma', price: 2500, rarity: 2,
    desc: 'Atravessa as nuvens sem fazer barulho... e às vezes nem aparece no espelho.',
    main: '#bfe6ff', headCol: '#e8f6ff', limb: '#9fc8e6', band: '#6a8fb0', visor: ['#2a3f55', '#0e1824'], eye: '#4adfff', alpha: 0.78,
    rim: 'rgba(255,255,255,0.95)',
    acc: { eyeGlow: '#4adfff', back: [{ type: 'wisp', col: '#d8f2ff' }] },
    trail: { kind: 'smoke', color: '#cfefff' }, aura: '#9fe0ff' }),
  skinPal({ id: 'ciber', name: 'Ciber Ninja', price: 2600, rarity: 2,
    desc: 'Metade ninja, metade máquina: os circuitos brilham quando ele acelera.',
    main: '#20242c', limb: '#2c313b', band: '#00b8d4', visor: ['#00323a', '#001418'], eye: '#00f0ff', rim: 'rgba(0,230,255,0.8)',
    acc: { eyeGlow: '#00f0ff', pads: { col: '#3a404c', neon: '#00e5ff' }, crest: { style: 'visorline', col: '#00e5ff' }, body: { pattern: 'circuit', col: '#00e5ff' } },
    trail: { kind: 'spark', color: '#00e5ff' }, aura: '#00e5ff' }),
  skinPal({ id: 'monge', name: 'Monge Estelar', price: 3500, rarity: 2,
    desc: 'Monge de uma galáxia distante; sua lâmina de luz zumbe no escuro.',
    main: '#8a6a48', limb: '#4a3624', band: '#3a2a1a', eye: '#cfefff',
    acc: { hood: { col: '#6b4f33' }, back: [{ type: 'sword', col: '#3a3f4a', blade: '#4adfff', glow: true }], body: { pattern: 'robe', col: '#d9c9a8' } },
    trail: { kind: 'star', color: '#9fe8ff' }, aura: '#4adfff' }),
  skinPal({ id: 'dragao', name: 'Mestre Dragão', price: 5000, rarity: 3,
    desc: 'Guardião ancestral da montanha de jade. Raríssimo.',
    main: '#1f9a6a', limb: '#145a40', band: '#c9a227', eye: '#ffe14d', rim: 'rgba(255,230,140,0.9)',
    acc: { horns: { style: 'dragon', col: '#e8c048' }, whiskers: '#e8c048', eyeGlow: '#ffe14d',
      back: [{ type: 'dtail', col: '#1f9a6a', col2: '#e8c048' }], body: { pattern: 'scales', col: '#e8c048' } },
    trail: { kind: 'spark', color: '#ffd23f' }, aura: '#ffd23f' }),
  // --- Torneio das Sombras: ninjas mascarados de cores marcantes (inspirados em jogos de luta clássicos; originais) ---
  skinPal({ id: 'lancaInfernal', name: 'Ninja da Lança Infernal', price: 4800, rarity: 3,
    desc: 'Volta do mundo das chamas com uma lança presa na corda: ninguém escapa do seu puxão.',
    main: '#1d1a16', limb: '#24201a', band: '#e8b81f', headCol: '#f2c21f', eye: '#ffffff', rim: 'rgba(255,200,80,0.9)',
    acc: { mask: { col: '#f2c21f', teeth: true }, eyeGlow: '#ffb030', back: [{ type: 'rope', col: '#c9a46a', blade: '#dfe5ee' }],
      body: { pattern: 'tabard', col: '#f2c21f' } },
    trail: { kind: 'fire', color: '#ff7a1a' }, aura: '#ff8a2a' }),
  skinPal({ id: 'geloEterno', name: 'Ninja do Gelo Eterno', price: 3200, rarity: 2,
    desc: 'Seu sopro congela até cachoeira e deixa um rastro de cristais de gelo.',
    main: '#1a1f2c', limb: '#20283a', band: '#2a8fe0', headCol: '#3aa0ff', eye: '#e8f8ff', rim: 'rgba(180,230,255,0.95)',
    acc: { mask: { col: '#2a8fe0' }, eyeGlow: '#bfeaff', breath: '#e8f8ff', body: { pattern: 'ice', col: '#9fe0ff' }, pads: { col: '#bfeaff' } },
    trail: { kind: 'frost', color: '#d8f4ff' }, aura: '#7fd0ff' }),
  skinPal({ id: 'pantano', name: 'Ninja do Pântano Ácido', price: 1800, rarity: 1,
    desc: 'Escamas verdes, língua comprida e passos que deixam gotas de ácido.',
    main: '#1b2216', limb: '#232c1c', band: '#3fae2a', headCol: '#46b830', eye: '#f5ff4a', rim: 'rgba(190,255,120,0.8)',
    acc: { mask: { col: '#3fae2a', scales: true }, eyeGlow: '#d4ff3a', body: { pattern: 'scales', col: '#6fdc4a' } },
    trail: { kind: 'acid', color: '#9dff3a' } }),
  skinPal({ id: 'nevoa', name: 'Ninja da Névoa Cinzenta', price: 1400, rarity: 1,
    desc: 'Vira fumaça no meio do pulo e reaparece do outro lado da parede.',
    main: '#2a2c32', limb: '#33363d', band: '#8a909c', headCol: '#9aa0aa', eye: '#ffffff', alpha: 0.9, rim: 'rgba(230,235,245,0.8)',
    acc: { mask: { col: '#8a909c' }, eyeGlow: '#e8eef8', body: { pattern: 'smoke', col: '#c9ced8' } },
    trail: { kind: 'smoke', color: '#b8bec8' } }),
  skinPal({ id: 'ciborgueRubro', name: 'Ninja Ciborgue Carmesim', price: 3000, rarity: 2,
    desc: 'Unidade de caça modelo LK-9: meio ninja, meio máquina, totalmente vermelho.',
    main: '#1c1c22', limb: '#2a2a32', band: '#d01c2a', headCol: '#c41a26', eye: '#ffffff', rim: 'rgba(255,120,120,0.8)',
    acc: { faceplate: { col: '#b8c0cc', eye: '#ff2a2a' }, eyeGlow: '#ff6a6a', pads: { col: '#8a929e', neon: '#ff2a3a' },
      bolts: '#8a909c', body: { pattern: 'panel', col: '#c41a26' } },
    trail: { kind: 'spark', color: '#ff4a3a' } }),
  skinPal({ id: 'veuVioleta', name: 'Kunoichi do Véu Violeta', price: 2200, rarity: 2,
    desc: 'Véu roxo, dois sais nas costas e um sorriso que ninguém nunca viu.',
    main: '#2a1730', limb: '#331c3a', band: '#c03ad8', headCol: '#b33acb', eye: '#ffffff', rim: 'rgba(240,160,255,0.85)',
    acc: { mask: { col: '#c03ad8' }, hair: { col: '#120a14' }, back: [{ type: 'sai', col: '#c03ad8', blade: '#dfe5ee' }],
      body: { pattern: 'tabard', col: '#c03ad8' } },
    trail: { kind: 'leaf', color: '#e07aff' } }),
  skinPal({ id: 'esmeralda', name: 'Dama das Lâminas Esmeralda', price: 2400, rarity: 2,
    desc: 'Seus leques de aço cortam o vento; deixa um brilho verde por onde passa.',
    main: '#16261e', limb: '#1c3026', band: '#1fa86a', headCol: '#22b573', eye: '#ffffff', rim: 'rgba(140,255,200,0.85)',
    acc: { mask: { col: '#1fa86a' }, hair: { col: '#0c140f' }, back: [{ type: 'fans', col: '#c9d2dc', col2: '#1fa86a' }],
      body: { pattern: 'tabard', col: '#1fa86a' } },
    trail: { kind: 'star', color: '#5affb0' } })
);
const RARITY_NAMES = ['Comum', 'Raro', 'Épico', 'Lendário'];
const RARITY_COLORS = ['#b8c2d0', '#4fb3ff', '#c77dff', '#ffc53a'];
let skin = SKINS[0];
